# permissions for end users to view stalesecretwatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stalesecretwatch-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stale-secrets-check
    app.kubernetes.io/part-of: stale-secrets-check
    app.kubernetes.io/managed-by: kustomize
  name: stalesecretwatch-viewer-role
rules:
- apiGroups:
  - github.com.github.com
  resources:
  - stalesecretwatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.com.github.com
  resources:
  - stalesecretwatches/status
  verbs:
  - get
