# permissions for end users to edit stalesecretwatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stalesecretwatch-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stale-secrets-watch
    app.kubernetes.io/part-of: stale-secrets-watch
    app.kubernetes.io/managed-by: kustomize
  name: stalesecretwatch-editor-role
rules:
- apiGroups:
  - security.stalesecretwatch.io
  resources:
  - stalesecretwatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.stalesecretwatch.io
  resources:
  - stalesecretwatches/status
  verbs:
  - get
