apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: stale-secrets-watch.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StaleSecretWatch is the Schema for the stalesecretwatches API
      displayName: Stale Secret Watch
      kind: StaleSecretWatch
      name: stalesecretwatches.security.stalesecretwatch.io
      specDescriptors:
      - description: RefreshInterval is the amount of time after which the Reconciler
          would watch the cluster Valid time units are "ns", "us" (or "µs"), "ms",
          "s", "m", "h" May be set to zero to fetch and create it once. Defaults to
          1h.
        displayName: Refresh Interval
        path: refreshInterval
      - description: StaleSecretToWatch points to the namespace and secret to watch
          for stale secrets.
        displayName: Stale Secret To Watch
        path: staleSecretToWatch
      - description: StaleThreshold defines the threshold (in days) beyond which a
          secret is considered stale.
        displayName: Stale Threshold In Days
        path: staleThresholdInDays
      statusDescriptors:
      - description: Conditions represent the current conditions of the StaleSecretWatch
          resource
        displayName: Conditions
        path: conditions
      version: v1beta1
  description: watches and notify stale secrets
  displayName: StaleSecretWatch
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ssw
  links:
  - name: Stale Secrets Watch
    url: https://stale-secrets-watch.domain
  maintainers:
  - email: souravpatnaik123@gmail.com
    name: souravpatnaik
  maturity: alpha
  provider:
    name: operator-sdk
  version: 0.0.0
